version: '2'
services:
  users-db:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: users
      MYSQL_HOST: users-db
  users-ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - "3001:3001"
    depends_on:
      - users-db
